name: apptinhtoan5ma
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  get: ^4.6.6
  shared_preferences: ^2.2.3
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/anhdaidienapp.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
 